#!/usr/bin/python

import matplotlib.pyplot as plt
import subprocess
import sys
import re
import getopt
import tempfile

# Use quicklook instead of printing to STDOUT
preview = False
marker = '.'

try:                                
    opts, args = getopt.getopt(sys.argv[1:], "pl")
except getopt.GetoptError:
    print "Unsupported option"
    sys.exit(2)
for opt, arg in opts:
    if opt in ("-p"):
        preview = True
    if opt in ("-l"):
        marker = '.-'

x = []
y = []   
for line in sys.stdin:
  line = line.strip()
  vals = re.split(r'\s+|\s*,\s*', line)
  x.append(vals[0])
  y.append(vals[1])
plt.plot(x, y, marker)
plt.minorticks_on()
plt.grid(which='both', color='#aaaaaa')

if (preview):
    with tempfile.NamedTemporaryFile(mode='w', suffix='.png') as f:
        plt.savefig(f.name, format='png')
        subprocess.check_call(['qlmanage', '-p', f.name], stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
else:
    plt.savefig(sys.stdout, format='png')

